"""Public Palace simulation-layer catalog helpers.

The public PDK owns the GDS layers that carry simulation-only boundary
geometry, while `gsim` owns how those layers are selected, meshed, and lowered
into Palace configuration. This module exposes the PDK side of that contract as
plain catalog data that notebooks can pass directly to
`PalaceSimBase.set_simulation_layers()`.

Surface EPR interface groups are generated by `gsim` from mesh/interface
identity. They are not PDK simulation-layer catalog entries.
"""

from __future__ import annotations

from typing import Any

from orpen_sc_pdk.tech import LAYER

PALACE_SIMULATION_BOUNDARY_LAYERS = {
    "D0_BOTTOM_SIM_BOUNDARY": LAYER.D0_BOTTOM_SIM_BOUNDARY,
    "D0_TOP_SIM_BOUNDARY": LAYER.D0_TOP_SIM_BOUNDARY,
    "D1_BOTTOM_SIM_BOUNDARY": LAYER.D1_BOTTOM_SIM_BOUNDARY,
    "D1_TOP_SIM_BOUNDARY": LAYER.D1_TOP_SIM_BOUNDARY,
}


def get_gsim_palace_simulation_layer_catalog() -> dict[str, dict[str, Any]]:
    """Return public simulation-only layer metadata for gsim."""

    return {
        name: {
            "gds_layer": (layer.layer, layer.datatype),
            "role": "solver_boundary_sheet",
            "stack_layer": name,
        }
        for name, layer in PALACE_SIMULATION_BOUNDARY_LAYERS.items()
    }


__all__ = [
    "get_gsim_palace_simulation_layer_catalog",
]
